Use redirect() instead of redirectLink()
PrestaShop/ps_cashondelivery pull request #42
Opened 2022-04-17 17:36 UTC by PrestaEdit

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Avoid using deprecated method (since PrestaShop 8).
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#28147.
| How to test?  | See inside the issue.

2022-04-17 18:27 UTC, Progi1984 reviewed
A Small change and it's ok

2022-04-17 18:27 UTC, Progi1984 commented on controllers/front/validation.php
> +        Tools::redirect('index.php?controller=order-confirmation?key=' . $customer->secure_key . '&id_cart=' . (int) $this->context->cart->id . '&id_module=' . (int) $this->module->id . '&id_order='
```suggestion
        Tools::redirect('index.php?controller=order-confirmation&key=' . $customer->secure_key . '&id_cart=' . (int) $this->context->cart->id . '&id_module=' . (int) $this->module->id . '&id_order=' . (int) $this->module->currentOrder);
```

2022-04-17 18:43 UTC, Progi1984 approved these changes

2022-05-04 14:28 UTC, kpodemski requested changes
This has been fixed already in this PR:
https://github.com/PrestaShop/ps_cashondelivery/pull/32

I suggest waiting for it instead of forcing the author to rebase 👍

2022-05-19 11:01 UTC, Progi1984 commented
@PrestaEdit Hi, could you resolve conflicts to this PR ? Thnaks

2022-05-19 11:02 UTC, PrestaEdit commented
If you say me that it's not for nothing (as Krystian told us: it could be part of another PR), I can.
If not, no :)

2022-05-19 11:10 UTC, kpodemski commented
Hello @PrestaEdit 

The PR I mention earlier was merged with a lot of bugfixes and improvements 🎉 

I think the problem from your PR has already been solved. Could you confirm? Thanks!

2022-05-19 11:37 UTC, PrestaEdit commented
As it's use redirect() instead of redirectLink(), yes.

We can now close this one.

2022-05-19 11:37 UTC, closed without merging